services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - 8000:8000
    env_file:
      - .env 
    command: >
      bash -c "
      prisma generate &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "